### ISSUE TITLE
Help needed deciphering CS QTL query

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#136] opened 2015-04-11 15:51 UTC
Piotr, I need your help with one query. Please see the QTL tab here http://www.interstoredb.org/Brassica/cs/. Then please check the CS_create_aux_tables_Queries_update_16_06_2014.txt file inside our dropbox folder and see the query responsible for rendering that table.

Can you explain to me what is exactly shown in the column second to last (Count scores)? It looks like it depends on some other temporary table/DB view...

**Comment by nowakowski** [comment] 2015-04-11 16:15
The query retrieves the value of a column called `count_score` - this is not defined in any of the standard model tables in the WHERE clause so it must be defined in `auxTraitsInterface` but I cannot find the definition of that entity anywhere in the file (or indeed in the project tree). Did you define such an entity (and if so - where)?

Perhaps you wanted `td.trait_scores_count` instead?

**Comment by Nuanda** [comment] 2015-04-11 16:16
Me? How could _I_ define it as we are talking the original CS queries here? :)

**Comment by nowakowski** [comment] 2015-04-11 16:17
Oh. Of course! Something is missing from the model / was not exported along with the database. I'll check if it's my problem or TGAC's problem...

**Comment by nowakowski** [comment] 2015-04-11 16:19
No, it's not one of mine. The original MySQL data dump does not include any such table/view/stored procedure. We need to ask @wjurkowski to take a look at this.

**Comment by Nuanda** [comment] 2015-04-11 16:21
Could it be it _somehow_ refers to the 'CREATE TABLE aux_trait_interface' definition (also present in the same file)?

**Comment by nowakowski** [comment] 2015-04-11 16:23
It's possible (but only possible!) - that table defines something like this:
`count(score_value) AS 'Count Scores'
...in which case this would simply be the number of `trait_scores` records retrieved for a given `trait_descriptor`.

**Comment by Nuanda** [comment] 2015-04-11 16:32
That's what I thought and that's what I tried to do in the code - see #137, app/models/qtl.rb file. However, I get different numbers...

Perhaps the counter itself, located in the TraitDescriptor (called `trait_scores_count`) is wrong? I don't know.

Can you see this PR and test, what's wrong with my query?

**Comment by nowakowski** [comment] 2015-04-11 17:16
The core of the problem is that there are multiple `trait_descriptors` with identical names.

The CropstoreDB application does something silly to circumvent this issue. What happens now is you're linking `processed_trait_datasets` with `trait_descriptors` on its primary key so you will only get those `trait_descriptors` which correspond to each `processed_trait_dataset`. This is not all of them - for example, with "erucic acid content" your query will only catch one (of three) `trait_descriptors` records.

There are ways around this (mostly involving outer joins) but rather than do do an SQL silly-walk the surefire solution would be to curate `trait_descriptors` in such a way that only one record shows up for each `descriptor_name`.

- go back to `trait_descriptors` and find all records which match the name

**Comment by nowakowski** [comment] 2015-04-11 17:17
Btw., I can perform the curation if you want. Might have to bounce this off @wjurkowski first.

**Comment by nowakowski** [comment] 2015-04-11 17:19
Oh, and since you asked -- no, the counter is correct.

**Comment by nowakowski** [comment] 2015-04-11 17:22
...although on the other hand if your counter-generating function made sure to insert the calculated value in *all* `trait_descriptor` records which share a given name, the problem would disappear.

**Comment by nowakowski** [comment] 2015-04-11 17:23
Yeah, I like to ramble. ^_^

**Comment by Nuanda** [comment] 2015-04-11 17:29
Wouldn't that make an incorrect counter, then? I prefer to curate the data, instead :).

**Comment by nowakowski** [comment] 2015-04-11 18:49
I need the go-ahead from @wjurkowski before I can do this.

**Comment by nowakowski** [comment] 2015-04-11 18:59
@wjurkowski What I would like to do is merge all `trait_descriptors` which share a given name into a single record. This would affect the following descriptors:

  - **seed oil content** (currently 2 records)
  - **host response to Albugo candida** (currently 2 records)
  - **erucic acid content** (currently 3 records)
  - **host response to Peronospora parasitica** (currently 4 records)
 
Can I do this? Is there a risk of misrepresenting/corrupting data?

**Comment by Nuanda** [comment] 2015-04-11 19:20
Pro tip: the answer "leave it for later curation" is not available in this particular quiz ;).

**Comment by sarahcayling** [comment] 2015-04-17 14:01
Hmm... I'm not sure that this is straightforward...
Seed oil content has 2 trait_descriptor_ids: hzau_SDOIL_01_LAB and hzau_SDOIL_02_LAB. The 01 is connected to the processed_trait_datasets table, whilst the 02 is connected to the trait_scores. Neither feature in trait_grades.

The 'Albugo' trait has 2 trait_descriptor_ids: hri_HRAC_01_GR and prt7_HRAC_02_GR, both of which have 409 trait_score records, and no trait_grades or processed_trait_dataset entries.

The 'erucic acid' trait has 3 trait_descriptor_ids like 'hzau_SDERUA_0*-LAB' where 03 is linked to 40 trait_score records and 01 and 02 are linked to 2 processed_trait_datasets each.

The 'Peronospora' trait has 4 records - each of which records a different strain of P. parasitica: P005, P006, P501 and P502) - merging these would lose that info. These have no entrie sin process_trait_datasets and 409 for '01' and '02' records each.

So, we can ignore trait_grades for these. But the records seem to be linked to different entries in the processed_trait_dataset and trait_score tables, so how do you plan to handle this with the proposed merging?

**Comment by Nuanda** [comment] 2015-05-06 21:11
@nowakowski Piotr, I believe this discussion requires your attention. Can you comment on Sarah's question?

**Comment by nowakowski** [comment] 2015-05-12 08:24
@sarahcayling Thank you for this explanation. We will refrain from merging records in `trait_descriptors`; instead we aggregate them by name in our GUI (so that when requesting a trait descriptor with a specific name, the system will serve data from all underlying records). Closing issue.

**Closed by nowakowski** 2015-05-12 08:24 UTC
Labels: help wanted, question
